### ISSUE TITLE
YouTube Bug

### ISSUE THREAD

**Issue by AbhanSindor** [CraftRom/Chidori-Kernel_onclite#3]
Lags some videos in youtube ROM:lineageos 19.1

**Comment by melles1991** [comment]
> Lags some videos in youtube ROM:lineageos 19.1

hi, sir. Please take me logcate
[How to capture logs](https://www.craft-rom.pp.ua/how-to/logcat)

[TELEGRAM-CHAT](http://t.me/craftrom) | [TELEGRAM-NEWS](http://t.me/craftrom_news)

**Comment by melles1991** [comment]
Next stable build fixed it
